import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "../components/homepage/Card";
import Navbar from "../components/Navbar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>
          GirlScipt Summer of Code 2022 | GirlScript Foundation India
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Rubik&display=swap');
        </style>
      </Head>

      <div className="flex flex-col items-center mb-24">
        <div className="flex flex-col w-[1136px]">
          <div className="flex flex-row justify-between">
            <div className="basis-1/2">
              <p className="text-black text-4xl font-extrabold mb-10">
                <span className="text-primary_orange-0 text-4xl font-extrabold">
                  GSSoC{" "}
                </span>
                2022
                <br />
                is here! &nbsp;
              </p>
              <p className="font-serif text-2xl text-black-100">
                GirlScript Summer of Code is a 3-month long
                <span className="text-primary_orange-0 text-2xl">
                &nbsp; #OpenSource &nbsp;
                </span>
                program by GirlScript Foundation.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col items-center mb-24">
        <div className="flex flex-col w-[1136px]">
          <div className="flex flex-row justify-between">
            <div className="basis-1/2">
              <img src="/assets/Rectangle.png" />
            </div>
            <div className="basis-1/2 order-last">
              <img src="/assets/GS_logo_Black.png" />
              <p className="text-primary_orange-0 text-4xl font-extrabold mb-10">
                <span className="text-black text-4xl font-extrabold">
                  About
                  <br />
                  GirlScript &nbsp;
                </span>
                Summer of Code
              </p>
              <p className="font-serif text-1xl text-black-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh
                pulvinar malesuada tortor orci nullam rhoncus et. Purus, massa
                orci aliquet neque. Nulla urna viverra tempus nullam commodo.
                Fringilla turpis sit laoreet pellentesque sit. Ultrices
                consequat tempor nisi, tincidunt tortor, elit pharetra, nulla.
                Enim a quam tortor, sodales. Vitae placerat egestas pellentesque
                senectus.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col items-center mb-24">
        <div className="flex flex-col w-[1136px]">
          <div className="flex flex-row justify-between">
            <div className="basis-1/2">
              <img src="/assets/GSSoC_logo_Black.png" />
              <p className="text-primary_orange-0 text-4xl font-extrabold mb-10">
                <span className="text-black text-4xl font-extrabold">
                  About
                  <br />
                  GirlScript &nbsp;
                </span>
                Summer of Code
              </p>
              <p className="font-serif text-1xl text-black-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque
                sit tortor aliquet mauris. Sodales odio vitae morbi nulla sit
                turpis sem at. Nibh in consectetur aliquam in ante pulvinar
                vehicula sed.
              </p>
            </div>
            <div className="basis-1/2 order-last">
              <div className="bg-primary_orange-0 px-4 py-4 rounded mr-3">
                <div className="grid grid-rows-3 grid-flow-col gap-3">
                  <div className="text-gray-200 text-3xl font-bold mb-2">
                    18k+
                    <br />
                    Registrations
                  </div>
                  <div className="text-gray-200 text-3xl font-bold mb-2">
                    135+
                    <br />
                    Institutes
                  </div>
                  <div className="text-gray-200 text-3xl font-bold mb-2">
                    112
                    <br />
                    Countries
                  </div>
                  <div className="text-gray-200 text-3xl font-bold mb-2">
                    40M+
                    <br />
                    Lines of Code
                  </div>
                  <div className="text-gray-200 text-3xl font-bold mb-2">
                    40M+
                    <br />
                    Pull Requests
                  </div>
                  <div className="text-gray-200 text-3xl font-bold mb-2">
                    17k+
                    <br />
                    Mentors
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Vishwa - https://github.com/GSSoC-Web/gssoc-website/projects/1#card-76402159 */}
      <div className="flex flex-col items-center mb-24">
        <div className="flex flex-col w-[1136px]">
          <p className="text-gray-200 text-5xl font-extrabold mb-10">
            Some of the{" "}
            <span className="text-primary_orange-0 text-5xl font-extrabold">
              participating Organisations!
            </span>
          </p>
          <div className="org__box flex flex-row items-center">
            {/* org1 */}
            <img
              className="w-20 h-auto mr-12"
              src="https://img.icons8.com/color/344/visual-studio-2019.png"
              alt="logo"
            />
            {/* org2 */}
            <img
              className="w-20 h-auto mr-12"
              src="https://img.icons8.com/color/344/visual-studio-2019.png"
              alt="logo"
            />
            {/* org3 */}
            <img
              className="w-20 h-auto mr-12"
              src="https://img.icons8.com/color/344/visual-studio-2019.png"
              alt="logo"
            />
            {/* org4 */}
            <img
              className="w-20 h-auto mr-12"
              src="https://img.icons8.com/color/344/visual-studio-2019.png"
              alt="logo"
            />
            <div>
              <p className="font-serif font-semibold text-3xl text-gray-200">
                and more...
              </p>
            </div>
          </div>
        </div>
      </div>
      {/* 


*/}
      <div className="main__wrapper flex flex-col items-center">
        {/* Be a part of GSSoC */}
        <div className="flex flex-col w-[1136px]">
          <p className="text-gray-200 text-5xl font-extrabold mb-10">
            <span className="text-primary_orange-0 text-5xl font-extrabold">
              Be a part of &nbsp;
            </span>
            GSSoC 2022!
          </p>
          <div className="flex flex-col items-center">
            {/* flexbox 1 */}
            <div className="flex flex-row items-start mb-3">
              <Card
                title="Participate in GSSoC 2022"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam"
                buttontext="Register"
              />
              <Card
                title="Be a Mentor"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam"
                buttontext="Register"
              />
            </div>
            {/* flexbox 2 */}
            <div className="flex flex-row items-start">
              <Card
                title="Submit your project"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam."
                buttontext="Know More"
              />
              <Card
                title="Be a Sponsor"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam."
                buttontext="Know More"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
