import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "../components/homepage/Card";
import Navbar from "../components/Navbar";
import Schedule from "../components/homepage/Schedule";
export default function Home() {
  return (
    <div>
      <Head>
        <title>
          GirlScipt Summer of Code 2022 | GirlScript Foundation India
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Rubik');
        </style>
      </Head>

      <div className="container mx-auto">
        <div className="first-section mb-10">
          <div className="basis-1/2">
            <p className="text-black font-semibold text-4xl 2.25rem 3rem mb-10">
              <span className="text-primary_orange-0">GSSoC </span>
              2022
              <br />
              is here! &nbsp;
            </p>
            <p className="font-serif font-medium text-2xl 1.5rem 2rem text-gray-800 mb-10">
              GirlScript Summer of Code is a 3-month long
              <br/>
              <span className="text-primary_orange-0">
                #OpenSource &nbsp;
              </span>
              program by GirlScript Foundation.
            </p>
            <div className="flex">
              <button className="bg-primary_orange-0 text-white font-bold py-3 px-5 rounded">
                Register Here
              </button>
              <p className="font-serif font-medium text-2xl 1.5rem 2rem text-primary_orange-0 m-2">
                Learn More
              </p>
            </div>
          </div>
          </div>

        <div className="flex flex-row justify-between mb-24">
          <div className="basis-1/2">
            <img src="/assets/Rectangle.png" />
          </div>
          <div className="basis-1/2 order-last">
            <img src="/assets/GS_logo_Black.png" />
            <p className="text-black font-semibold text-4xl 2.25rem 3rem mb-5">
              About &nbsp;
              <span className="text-primary_orange-0">GirlScript &nbsp;</span>
              Foundation
            </p>
            <p className="font-serif text-1xl text-black-100">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh
              pulvinar malesuada tortor orci nullam rhoncus et. Purus, massa
              orci aliquet neque. Nulla urna viverra tempus nullam commodo.
              Fringilla turpis sit laoreet pellentesque sit. Ultrices consequat
              tempor nisi, tincidunt tortor, elit pharetra, nulla. Enim a quam
              tortor, sodales. Vitae placerat egestas pellentesque senectus.
            </p>
          </div>
        </div>

        <div className="flex flex-row justify-between  mb-24">
          <div className="basis-1/2">
            <img src="/assets/GSSoC_logo_Black.png" />
            <p className="text-primary_orange-0 font-semibold text-4xl 2.25rem 3rem mb-10">
              <span className="text-black text-4xl 2.25rem 3rem">
                About
                <br />
                GirlScript &nbsp;
              </span>
              Summer of Code
            </p>
            <p className="font-serif text-xl 1.25rem 1.75rem">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque sit
              tortor aliquet mauris. Sodales odio vitae morbi nulla sit turpis
              sem at. Nibh in consectetur aliquam in ante pulvinar vehicula sed.
            </p>
          </div>
          <div className="basis-1/2 order-last">
            {/* <div className="bg-primary_orange-0 px-4 py-4 rounded mr-3">
              <div className="grid grid-rows-3 grid-flow-col gap-3">
                <div className="text-gray-200 text-3xl font-bold ">
                  18k+
                  <br />
                  Registrations
                </div>
                <div className="text-gray-200 text-3xl font-bold ">
                  135+
                  <br />
                  Institutes
                </div>
                <div className="text-gray-200 text-3xl font-bold ">
                  112
                  <br />
                  Countries
                </div>
                <div className="text-gray-200 text-3xl font-bold ">
                  40M+
                  <br />
                  Lines of Code
                </div>
                <div className="text-gray-200 text-3xl font-bold ">
                  40M+
                  <br />
                  Pull Requests
                </div>
                <div className="text-gray-200 text-3xl font-bold ">
                  17k+
                  <br />
                  Mentors
                </div>
              </div>
            </div> */}
          </div>
        </div>
  
        <div className="organisation mb-24">
          <p className="font-serif font-semibold text-gray-800 text-4xl 2.25rem 3rem">
            Some of the{" "}
            <span className="text-primary_orange-0 text-4xl 2.25rem 3rem">
              participating organisations!
            </span>
          </p>
          <div className="org__box flex flex-row items-center flex-wrap">
            <img
              className="w-20 h-auto mr-12"
              src="https://github.com/GSSoC-Web/gssoc-assets/blob/main/Participating_projects/logo1.png?raw=true"
              alt="logo"
            />
            <img
              className="w-20 h-auto mr-12"
              src="https://github.com/GSSoC-Web/gssoc-assets/blob/main/Participating_projects/logo2.png?raw=true"
              alt="logo"
            />
            <img
              className="w-20 h-auto mr-12"
              src="https://github.com/GSSoC-Web/gssoc-assets/blob/main/Participating_projects/logo3.png?raw=true"
              alt="logo"
            />
            <img
              className="w-20 h-auto mr-12"
              src="https://github.com/GSSoC-Web/gssoc-assets/blob/main/Participating_projects/logo4.png?raw=true"
              alt="logo"
            />
            <div>
              <p className="font-serif font-medium text-4xl text-gray-800">
                and more ...
              </p>
            </div>
          </div>
        </div>
        <div className="be-part-of mb-24">
          <p className="font-serif font-semibold text-justify text-gray-800 text-4xl 2.25rem 3rem ">
            <span className="text-primary_orange-0 text-4xl 2.25rem 3rem">
              Be a part of &nbsp;
            </span>
            GSSoC 2022!
          </p>
          <div className="flex justify-between flex-wrap  ">
            {/* flexbox 1 */}
            <div className="flex justify-between flex-wrap ">
              <Card
                title="Participate in GSSoC 2022"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam"
                buttontext="Register"
              />
              <Card
                title="Be a Mentor"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam"
                buttontext="Register"
              />
            </div>
            {/* flexbox 2 */}
            <div className="flex justify-between flex-wrap ">
              <Card
                title="Submit your project"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam."
                buttontext="Know More"
              />
              <Card
                title="Be a Sponsor"
                content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae libero cumque impedit molestias sequi voluptas delectus laborum, ex quam."
                buttontext="Know More"
              />
            </div>
          </div>
        </div>
      </div>
      {/* sponsors */}
      <div className="sponsors__container flex flex-row justify-center">
        <div className="sponsors__wrapper flex flex-col w-[1136px] mt-[93px]">
          <div className="sponsors__header mb-9">
            <p className="font-serif font-semibold text-gray-800 text-4xl leading-10">
              Our Sponsors
            </p>
          </div>
          {/* sponsors card container */}
          <div className="sponsors__card__container flex flex-row justify-between">
            {/* card1 */}
            <div className="sponsor__card__wrapper w-[368px] h-[228px] px-9 py-9 shadow-xl rounded">
              <p className="text-[#ff7a19] font-serif font-semibold text-3xl mb-9">
                Gold Sponsor
              </p>
              <img
                src="https://gssoc.girlscript.tech/images/sponsor/2021/do_blue.svg"
                alt="logo"
              />
            </div>
            {/* card2 */}
            <div className="sponsor__card__wrapper w-[368px] h-[228px] px-9 py-9 shadow-xl rounded">
              <p className="text-[#ff7a19] font-serif font-semibold text-3xl  mb-9">
                Silver Sponsor
              </p>
              <img
                src="https://gssoc.girlscript.tech/images/sponsor/2021/linode.svg"
                alt="logo"
              />
            </div>
            {/* card3 */}
            <div className="sponsor__card__wrapper w-[368px] h-[228px] px-9 py-9 shadow-xl rounded">
              <p className="text-[#ff7a19] font-serif font-semibold text-3xl  mb-9">
                Bronze Sponsor
              </p>
              <img
                src="https://gssoc.girlscript.tech/images/sponsor/2021/honeybadger.svg"
                alt="logo"
              />
            </div>
          </div>
          <div className="other__sponsors px-9 py-9 shadow-xl rounded mt-9">
            <div className="other__sponsors__title">
              <p className="text-[#ff7a19] font-serif font-semibold text-3xl  mb-9">
                Other Sponsors
              </p>
            </div>
            {/* row 1 */}
            <div className="sponsors__row__one flex flex-row mb-9">
              <img
                className="h-12 mr-14"
                src="https://gssoc.girlscript.tech/images/sponsor/2021/taskade-logo.png"
                alt="logo"
              />
              <img
                className="h-12 mr-14"
                src="https://gssoc.girlscript.tech/images/sponsor/2021/sticker-mule.png"
                alt="logo"
              />
              <img
                className="h-12 mr-14"
                src="https://gssoc.girlscript.tech/images/sponsor/2021/xyz-logo-color.png"
                alt="logo"
              />
            </div>
            <div className="sponsors__row__two flex flex-row">
              <img
                className="h-12 mr-14"
                src="https://gssoc.girlscript.tech/images/sponsor/2021/sketch-logo-light.png"
                alt="logo"
              />
              <img
                className="h-12 mr-14"
                src="https://gssoc.girlscript.tech/images/sponsor/2021/egghead_logo.png"
                alt="logo"
              />
              <img
                className="h-12 mr-14"
                src="https://gssoc.girlscript.tech/images/sponsor/2021/ORM_logo_red_rgb.png"
                alt="logo"
              />
            </div>
          </div>
        </div>
      </div>
      {/* Schedule */}
      <Schedule />
    </div>
  );
}
